<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('products')->delete();

        \DB::table('products')->insert(array (
            0 =>
            array (
                'id' => 1,
                'category_id' => 2,
                'brand_id' => 2,
                'name' => 'I Phone 15',
                'slug' => 'i-phone-15',
                'image' => '["products/01K4T0Z2KPDFX42SHAHP6KD714.jpg", "products/01K4T0ZGFMQ62HQMM7EC12WFBP.jpg"]',
                'description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has',
                'price' => '100000.00',
                'stock' => 1,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-10 14:37:37',
                'updated_at' => '2025-09-10 14:37:51',
            ),
            1 =>
            array (
                'id' => 2,
                'category_id' => 2,
                'brand_id' => 1,
                'name' => 'Samsung Galaxy S25 Ultra',
                'slug' => 'samsung-galaxy-s25-ultra',
                'image' => '["products/samsung-s25.jpg"]',
                'description' => 'Experience the future of mobile technology with the Samsung Galaxy S25 Ultra. Featuring an advanced AI camera system and unprecedented processing power.',
                'price' => '95000.00',
                'stock' => 15,
                'is_active' => 1,
                'is_featured' => 1,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            2 =>
            array (
                'id' => 3,
                'category_id' => 1,
                'brand_id' => 3,
                'name' => 'MacBook Pro M3 Max',
                'slug' => 'macbook-pro-m3-max',
                'image' => '["products/macbook-m3.jpg"]',
                'description' => 'The most powerful MacBook ever. Features the groundbreaking M3 Max chip for unparalleled performance and efficiency.',
                'price' => '250000.00',
                'stock' => 8,
                'is_active' => 1,
                'is_featured' => 1,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            3 =>
            array (
                'id' => 4,
                'category_id' => 3,
                'brand_id' => 4,
                'name' => 'Sony WH-1000XM6',
                'slug' => 'sony-wh-1000xm6',
                'image' => '["products/sony-headphones.jpg"]',
                'description' => 'Industry-leading noise cancellation headphones with AI-enhanced audio processing and 40-hour battery life.',
                'price' => '45000.00',
                'stock' => 20,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 1,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            4 =>
            array (
                'id' => 5,
                'category_id' => 4,
                'brand_id' => 5,
                'name' => 'LG OLED G5 65-inch',
                'slug' => 'lg-oled-g5-65',
                'image' => '["products/lg-tv.jpg"]',
                'description' => 'Revolutionary OLED TV with perfect blacks, infinite contrast, and advanced gaming features.',
                'price' => '300000.00',
                'stock' => 5,
                'is_active' => 1,
                'is_featured' => 1,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            5 =>
            array (
                'id' => 6,
                'category_id' => 2,
                'brand_id' => 6,
                'name' => 'Google Pixel 9 Pro',
                'slug' => 'google-pixel-9-pro',
                'image' => '["products/pixel-9.jpg"]',
                'description' => 'The ultimate AI phone with revolutionary photography capabilities and pure Android experience.',
                'price' => '85000.00',
                'stock' => 12,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            6 =>
            array (
                'id' => 7,
                'category_id' => 6,
                'brand_id' => 7,
                'name' => 'DJI Air 3S',
                'slug' => 'dji-air-3s',
                'image' => '["products/dji-drone.jpg"]',
                'description' => 'Professional-grade drone with 8K camera and advanced obstacle avoidance system.',
                'price' => '120000.00',
                'stock' => 7,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            7 =>
            array (
                'id' => 8,
                'category_id' => 3,
                'brand_id' => 1,
                'name' => 'Samsung Galaxy Book 4 Pro',
                'slug' => 'samsung-galaxy-book-4-pro',
                'image' => '["products/samsung-laptop.jpg"]',
                'description' => 'Ultra-thin laptop with AMOLED display and seamless Galaxy ecosystem integration.',
                'price' => '180000.00',
                'stock' => 10,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 1,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            8 =>
            array (
                'id' => 9,
                'category_id' => 4,
                'brand_id' => 2,
                'name' => 'Apple AirPods Pro 3',
                'slug' => 'apple-airpods-pro-3',
                'image' => '["products/airpods-pro.jpg"]',
                'description' => 'Next-generation AirPods with enhanced spatial audio and improved active noise cancellation.',
                'price' => '35000.00',
                'stock' => 25,
                'is_active' => 1,
                'is_featured' => 1,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            9 =>
            array (
                'id' => 10,
                'category_id' => 7,
                'brand_id' => 8,
                'name' => 'Canon EOS R7 Mark II',
                'slug' => 'canon-eos-r7-mark-ii',
                'image' => '["products/canon-camera.jpg"]',
                'description' => 'Professional mirrorless camera with advanced autofocus and 6K video capabilities.',
                'price' => '220000.00',
                'stock' => 6,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            10 =>
            array (
                'id' => 11,
                'category_id' => 8,
                'brand_id' => 9,
                'name' => 'Xbox Series X Pro',
                'slug' => 'xbox-series-x-pro',
                'image' => '["products/xbox-console.jpg"]',
                'description' => 'Next-gen gaming console with 12K gaming support and revolutionary cloud gaming integration.',
                'price' => '150000.00',
                'stock' => 15,
                'is_active' => 1,
                'is_featured' => 1,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            11 =>
            array (
                'id' => 12,
                'category_id' => 9,
                'brand_id' => 10,
                'name' => 'Garmin Fenix 9 Pro',
                'slug' => 'garmin-fenix-9-pro',
                'image' => '["products/garmin-watch.jpg"]',
                'description' => 'Premium multisport GPS watch with advanced training features and 30-day battery life.',
                'price' => '75000.00',
                'stock' => 18,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 1,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            12 =>
            array (
                'id' => 13,
                'category_id' => 10,
                'brand_id' => 11,
                'name' => 'Bose Smart Soundbar 1000',
                'slug' => 'bose-smart-soundbar-1000',
                'image' => '["products/bose-soundbar.jpg"]',
                'description' => 'Premium soundbar with Dolby Atmos and AI-powered room calibration.',
                'price' => '90000.00',
                'stock' => 9,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            13 =>
            array (
                'id' => 14,
                'category_id' => 2,
                'brand_id' => 12,
                'name' => 'OnePlus 15 Pro',
                'slug' => 'oneplus-15-pro',
                'image' => '["products/oneplus-phone.jpg"]',
                'description' => 'Flagship killer with revolutionary charging technology and premium build quality.',
                'price' => '70000.00',
                'stock' => 14,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            14 =>
            array (
                'id' => 15,
                'category_id' => 4,
                'brand_id' => 2,
                'name' => 'Apple Vision Pro 2',
                'slug' => 'apple-vision-pro-2',
                'image' => '["products/vision-pro.jpg"]',
                'description' => 'Next-generation mixed reality headset with groundbreaking spatial computing capabilities.',
                'price' => '350000.00',
                'stock' => 4,
                'is_active' => 1,
                'is_featured' => 1,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
            15 =>
            array (
                'id' => 16,
                'category_id' => 3,
                'brand_id' => 13,
                'name' => 'Dyson Zone Air',
                'slug' => 'dyson-zone-air',
                'image' => '["products/dyson-purifier.jpg"]',
                'description' => 'Personal air purification headphones with active noise cancellation.',
                'price' => '65000.00',
                'stock' => 11,
                'is_active' => 1,
                'is_featured' => 0,
                'in_stock' => 1,
                'in_sale' => 0,
                'created_at' => '2025-09-22 10:00:00',
                'updated_at' => '2025-09-22 10:00:00',
            ),
        ));


    }
}
